name: Release
on: push
jobs:
    build:
      runs-on: ubuntu-24.04
      steps:
        - uses: actions/checkout@v4
        - uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: remla25-team2-bot
            password: ${{ secrets.GHBOT_TOKEN }}
        - run: |
            IMG="ghcr.io/${{github.repository}}"
            IMG=${IMG@L}
            docker build --tag $IMG:latest .
            docker push --all-tags $IMG
